#!/bin/bash

set -eufo pipefail

split_inline_sig () {
	local inreldest reldest relsigdest
	inreldest="$1"
	reldest="$2"
	relsigdest="$3"

	# Note: InRelease files are fun since one needs to remove the
	# last newline from the PGP SIGNED MESSAGE part, while keeping
	# the PGP SIGNATURE part intact. This shell implementation
	# should work on most if not all systems, instead of trying to
	# sed/tr/head, etc.
	rm -f "$reldest" "$relsigdest"
	nl=""
	state="pre-begin"
	while IFS= read -r line; do
		case "${state}" in
			pre-begin)
			if [ "x${line}" = "x-----BEGIN PGP SIGNED MESSAGE-----" ]; then
				state="begin"
			fi
			;;
			begin)
			if [ "x${line}" = "x" ]; then
				state="data"
			fi
			;;
			data)
			if [ "x${line}" = "x-----BEGIN PGP SIGNATURE-----" ]; then
				printf "%s\n" "${line}" > "$relsigdest"
				state="signature"
			else
				printf "${nl}%s" "${line}" >> "$reldest"
				nl="\n"
			fi
			;;
			signature)
			printf "%s\n" "${line}" >> "$relsigdest"
			if [ "x${line}" = "x-----END PGP SIGNATURE-----" ]; then
				break
			fi
		esac
	done < "$inreldest"
}

gpg --generate-key --batch << EOF
%no-protection
Key-Type: eddsa
Key-Curve: ed25519
Key-Usage: sign
Name-Real: root
EOF

# printf 'a\nb\nc\nd\n' | gpg --clearsign > InRelease

cat << EOF | gpg --clearsign > InRelease
Codename: snapshot
Components: main
Architectures: all amd64 arm64
Date: Fri, 24 Nov 2023 00:08:59 +0000
Valid-Until:
SHA256:
 2bc1a3f01791ae7bfcfb4771c5445367555247343d03965fa210f617207d5663 3695508 main/binary-all/Packages.xz
 0040fdf2f957703650c54fc39599bbe0df09dd51bb22ce36299d3bee5496d166 7838940 main/binary-amd64/Packages.xz
 b6d9988e0c11521d45a2e42df05c166d42a1b4e5baca3020e4272a58cf7b5000 7756136 main/binary-arm64/Packages.xz
 ffa5f520cb000a011135377ed5d7632d07c586729adf7540c931c6f77cba14c5 9982048 main/source/Sources.xz
EOF

cat InRelease

touch ./keyring.gpg
gpg --export | gpg --no-default-keyring --keyring ./keyring.gpg --import
split_inline_sig InRelease Release Release.gpg
gpgv --keyring ./keyring.gpg InRelease
gpgv --keyring ./keyring.gpg Release.gpg Release
