#!/bin/bash

set -eufo pipefail

split_inline_sig () {
	local inreldest reldest relsigdest
	inreldest="$1"
	reldest="$2"
	relsigdest="$3"

	# Note: InRelease files are fun since one needs to remove the
	# last newline from the PGP SIGNED MESSAGE part, while keeping
	# the PGP SIGNATURE part intact. This shell implementation
	# should work on most if not all systems, instead of trying to
	# sed/tr/head, etc.
	rm -f "$reldest" "$relsigdest"
	nl=""
	state="pre-begin"
	while IFS= read -r line; do
		case "${state}" in
			pre-begin)
			if [ "x${line}" = "x-----BEGIN PGP SIGNED MESSAGE-----" ]; then
				state="begin"
			fi
			;;
			begin)
			if [ "x${line}" = "x" ]; then
				state="data"
			fi
			;;
			data)
			if [ "x${line}" = "x-----BEGIN PGP SIGNATURE-----" ]; then
				printf "%s\n" "${line}" > "$relsigdest"
				state="signature"
			else
				printf "${nl}%s" "${line}" >> "$reldest"
				nl="\n"
			fi
			;;
			signature)
			printf "%s\n" "${line}" >> "$relsigdest"
			if [ "x${line}" = "x-----END PGP SIGNATURE-----" ]; then
				break
			fi
		esac
	done < "$inreldest"
}

gpg --generate-key --batch << EOF
%no-protection
Key-Type: eddsa
Key-Curve: ed25519
Key-Usage: sign
Name-Real: root
EOF

printf 'a\nb\nc\nd\n' | gpg --clearsign > InRelease
touch ./keyring.gpg
gpg --export | gpg --no-default-keyring --keyring ./keyring.gpg --import
split_inline_sig InRelease Release Release.gpg
gpgv --keyring ./keyring.gpg InRelease
gpgv --keyring ./keyring.gpg Release.gpg Release
